---
title: "BM_OU_question"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### The project root 
```{r define data root and import tree}
#load required package
library(ape)
#import and define data
project_root <- 'C:/Users/Esther/Documents/Master/Stage/'
```

### Import data 
```{r import data}
#import trait table 
woody_tsv_file <- paste(c(project_root, 'sdmdl-angiosperm-data/data/woody.tsv'), collapse = '')
woody_tsv <- read.table(woody_tsv_file, sep = '\t', header = TRUE)

#load tree
tree_file <- paste(c(project_root, 'ALLMB.tre'), collapse = '')
tree <- read.tree(tree_file)

#load GIS data 
GIS_file <- paste(c(project_root, 'niche_traits_merged.csv'), collapse = '')
GIS <- read.table(GIS_file, sep = ',', header = TRUE)
```

### Define formulas
```{r}
#best model (for both BM and OU)
woody_formula_25a <- woody ~ Aspect + BulkDensity + ClayPercentage + monthCountByTemp10 + PETDriestQuarter + PETWettestQuarter + OrganicCarbon + PhCaCL + Slope + bio2 + bio5 + bio14 + bio15 + bio18 + bio19
```

### Model selection
```{r}
library(phylolm)

#BM model selection
phylostep(formula = woody_formula_25a, starting.formula = woody_starting_formula, data = GIS_woody, phy = tree_woody, model = "BM", direction = "both", trace = 2)

#OU model selection
phylostep(formula = woody_formula_8c, starting.formula = woody_starting_formula, data = GIS_woody, phy = tree_woody, model = "OUfixedRoot", direction = "both", trace = 2, lower.bound = 0, upper.bound = 1000)
```
